/**
 * Generated types from canvas: Graph Converter Execution
 *
 * DO NOT EDIT MANUALLY - This file is auto-generated
 * Generated by @principal-ai/principal-view-core
 *
 * Canvas: No description
 * Version: 1.0.0
 */

/**
 * Event type for node: graph-converter-1
 */
export namespace GraphConverter1 {
  /**
   * Triggered when graph conversion begins
   */
  export interface ConversionStarted {
    name: 'conversion.started';
    attributes: {
      /** Number of node types in config */
      'config.nodeTypes': number;
      /** Number of edge types in config */
      'config.edgeTypes': number;
    };
  }

  /**
   * Event type for graph-converter-1
   */
  export type Event = ConversionStarted;

  /**
   * Event name for graph-converter-1
   */
  export type EventName = 'conversion.started';
}

/**
 * Event type for node: graph-converter-2
 */
export namespace GraphConverter2 {
  /**
   * Triggered during node processing
   */
  export interface ConversionProcessingNodes {
    name: 'conversion.processingNodes';
    attributes: {
      /** Number of nodes being processed */
      'nodes.count': number;
    };
  }

  /**
   * Event type for graph-converter-2
   */
  export type Event = ConversionProcessingNodes;

  /**
   * Event name for graph-converter-2
   */
  export type EventName = 'conversion.processingNodes';
}

/**
 * Event type for node: graph-converter-3
 */
export namespace GraphConverter3 {
  /**
   * Triggered during edge processing
   */
  export interface ConversionProcessingEdges {
    name: 'conversion.processingEdges';
    attributes: {
      /** Number of edges being processed */
      'edges.count': number;
    };
  }

  /**
   * Event type for graph-converter-3
   */
  export type Event = ConversionProcessingEdges;

  /**
   * Event name for graph-converter-3
   */
  export type EventName = 'conversion.processingEdges';
}

/**
 * Event type for node: graph-converter-4
 */
export namespace GraphConverter4 {
  /**
   * Triggered when conversion completes successfully
   */
  export interface ConversionComplete {
    name: 'conversion.complete';
    attributes: {
      /** Number of nodes in result */
      'result.nodes.count': number;
      /** Number of edges in result */
      'result.edges.count': number;
      /** Conversion duration in milliseconds */
      'duration.ms'?: number;
    };
  }

  /**
   * Event type for graph-converter-4
   */
  export type Event = ConversionComplete;

  /**
   * Event name for graph-converter-4
   */
  export type EventName = 'conversion.complete';
}

/**
 * Event type for node: graph-converter-5
 */
export namespace GraphConverter5 {
  /**
   * Triggered when conversion fails
   */
  export interface ConversionError {
    name: 'conversion.error';
    attributes: {
      /** Error message */
      'error.message': string;
      /** Phase where error occurred */
      'error.phase'?: string;
    };
  }

  /**
   * Event type for graph-converter-5
   */
  export type Event = ConversionError;

  /**
   * Event name for graph-converter-5
   */
  export type EventName = 'conversion.error';
}

/**
 * Event type for node: validation-1
 */
export namespace Validation1 {
  /**
   * Triggered when validation begins
   */
  export interface ValidationStarted {
    name: 'validation.started';
    attributes: {
      /** Size of configuration being validated */
      'config.size': number;
    };
  }

  /**
   * Event type for validation-1
   */
  export type Event = ValidationStarted;

  /**
   * Event name for validation-1
   */
  export type EventName = 'validation.started';
}

/**
 * Event type for node: validation-2
 */
export namespace Validation2 {
  /**
   * Triggered when validation completes
   */
  export interface ValidationComplete {
    name: 'validation.complete';
    attributes: {
      /** Whether validation passed */
      'validation.passed': boolean;
      /** Number of validation errors */
      'errors.count': number;
    };
  }

  /**
   * Event type for validation-2
   */
  export type Event = ValidationComplete;

  /**
   * Event name for validation-2
   */
  export type EventName = 'validation.complete';
}

/**
 * Union of all event names in the canvas
 */
export type AllEventNames = 'conversion.started' | 'conversion.processingNodes' | 'conversion.processingEdges' | 'conversion.complete' | 'conversion.error' | 'validation.started' | 'validation.complete';

/**
 * Type-safe event emitter for a specific node
 *
 * @example
 * ```typescript
 * const emit: NodeEmitter<GraphConverter.EventName, GraphConverter.Event> = ...
 * emit('conversion.started', {
 *   name: 'conversion.started',
 *   attributes: { ... }
 * });
 * ```
 */
export type NodeEmitter<
  TEventName extends string,
  TEvent extends { name: TEventName; attributes: Record<string, any> }
> = (event: TEvent) => void;

/**
 * Type-safe event emitter by event name
 *
 * @example
 * ```typescript
 * const emit: NodeEmitterByName<GraphConverter.Event> = ...
 * emit('conversion.started', {
 *   'config.nodeTypes': 2,
 *   'config.edgeTypes': 1
 * });
 * ```
 */
export type NodeEmitterByName<
  TEvent extends { name: string; attributes: Record<string, any> }
> = <TName extends TEvent['name']>(
  eventName: TName,
  attributes: Extract<TEvent, { name: TName }>['attributes']
) => void;