/**
 * Generated types from canvas: Graph Converter Execution
 *
 * DO NOT EDIT MANUALLY - This file is auto-generated
 * Generated by @principal-ai/principal-view-core
 *
 * Canvas: No description
 * Version: 1.0.0
 */

/**
 * Event types for component: graph-converter
 */
export namespace GraphConverter {
  /**
   * Triggered when graph conversion begins
   */
  export interface ConversionStarted {
    name: 'conversion.started';
    attributes: {
      /** Number of node types in config */
      'config.nodeTypes': number;
      /** Number of edge types in config */
      'config.edgeTypes': number;
    };
  }

  /**
   * Triggered during node processing
   */
  export interface ConversionProcessingNodes {
    name: 'conversion.processingNodes';
    attributes: {
      /** Number of nodes being processed */
      'nodes.count': number;
    };
  }

  /**
   * Triggered during edge processing
   */
  export interface ConversionProcessingEdges {
    name: 'conversion.processingEdges';
    attributes: {
      /** Number of edges being processed */
      'edges.count': number;
    };
  }

  /**
   * Triggered when conversion completes successfully
   */
  export interface ConversionComplete {
    name: 'conversion.complete';
    attributes: {
      /** Number of nodes in result */
      'result.nodes.count': number;
      /** Number of edges in result */
      'result.edges.count': number;
      /** Conversion duration in milliseconds */
      'duration.ms'?: number;
    };
  }

  /**
   * Triggered when conversion fails
   */
  export interface ConversionError {
    name: 'conversion.error';
    attributes: {
      /** Error message */
      'error.message': string;
      /** Phase where error occurred */
      'error.phase'?: string;
    };
  }

  /**
   * All event types for graph-converter
   */
  export type Event = ConversionStarted | ConversionProcessingNodes | ConversionProcessingEdges | ConversionComplete | ConversionError;

  /**
   * All event names for graph-converter
   */
  export type EventName = 'conversion.started' | 'conversion.processingNodes' | 'conversion.processingEdges' | 'conversion.complete' | 'conversion.error';
}

/**
 * Event types for component: validation
 */
export namespace Validation {
  /**
   * Triggered when validation begins
   */
  export interface ValidationStarted {
    name: 'validation.started';
    attributes: {
      /** Size of configuration being validated */
      'config.size': number;
    };
  }

  /**
   * Triggered when validation completes
   */
  export interface ValidationComplete {
    name: 'validation.complete';
    attributes: {
      /** Whether validation passed */
      'validation.passed': boolean;
      /** Number of validation errors */
      'errors.count': number;
    };
  }

  /**
   * All event types for validation
   */
  export type Event = ValidationStarted | ValidationComplete;

  /**
   * All event names for validation
   */
  export type EventName = 'validation.started' | 'validation.complete';
}

/**
 * Event types for component: graph-output
 */
export namespace GraphOutput {
  /**
   * Triggered when output is created
   */
  export interface OutputCreated {
    name: 'output.created';
    attributes: {
      /** Type of output created */
      'output.type': string;
    };
  }

  /**
   * All event types for graph-output
   */
  export type Event = OutputCreated;

  /**
   * All event names for graph-output
   */
  export type EventName = 'output.created';
}

/**
 * Union of all event names in the canvas
 */
export type AllEventNames = 'conversion.started' | 'conversion.processingNodes' | 'conversion.processingEdges' | 'conversion.complete' | 'conversion.error' | 'validation.started' | 'validation.complete' | 'output.created';

/**
 * Type-safe event emitter for a specific node
 *
 * @example
 * ```typescript
 * const emit: NodeEmitter<GraphConverter.EventName, GraphConverter.Event> = ...
 * emit('conversion.started', {
 *   name: 'conversion.started',
 *   attributes: { ... }
 * });
 * ```
 */
export type NodeEmitter<
  TEventName extends string,
  TEvent extends { name: TEventName; attributes: Record<string, any> }
> = (event: TEvent) => void;

/**
 * Type-safe event emitter by event name
 *
 * @example
 * ```typescript
 * const emit: NodeEmitterByName<GraphConverter.Event> = ...
 * emit('conversion.started', {
 *   'config.nodeTypes': 2,
 *   'config.edgeTypes': 1
 * });
 * ```
 */
export type NodeEmitterByName<
  TEvent extends { name: string; attributes: Record<string, any> }
> = <TName extends TEvent['name']>(
  eventName: TName,
  attributes: Extract<TEvent, { name: TName }>['attributes']
) => void;