/**
 * Generated types from canvas: Validation Pipeline
 *
 * DO NOT EDIT MANUALLY - This file is auto-generated
 * Generated by @principal-ai/principal-view-core
 *
 * Canvas: Complete validation workflow from codebase composition analysis through validation to results
 * Version: 1.0.0
 */

/**
 * Event type for node: analysis-started
 */
export namespace AnalysisStarted {
  /**
   * undefined
   */
  export interface AnalysisStarted {
    name: 'analysis.started';
    attributes: {
      /** Repository root path */
      'repository.path': string;
      /** Type of analysis (discovery, validation, full) */
      'analysis.type': string;
    };
  }

  /**
   * Event type for analysis-started
   */
  export type Event = AnalysisStarted;

  /**
   * Event name for analysis-started
   */
  export type EventName = 'analysis.started';
}

/**
 * Event type for node: filetree-built
 */
export namespace FiletreeBuilt {
  /**
   * undefined
   */
  export interface FiletreeBuilt {
    name: 'filetree.built';
    attributes: {
      /** Total files in repository */
      'files.total': any;
      /** Content hash for caching */
      'filetree.sha': string;
    };
  }

  /**
   * Event type for filetree-built
   */
  export type Event = FiletreeBuilt;

  /**
   * Event name for filetree-built
   */
  export type EventName = 'filetree.built';
}

/**
 * Event type for node: packages-discovered
 */
export namespace PackagesDiscovered {
  /**
   * undefined
   */
  export interface PackagesDiscovered {
    name: 'packages.discovered';
    attributes: {
      /** Number of packages found */
      'packages.count': any;
      /** Package names */
      'packages.names'?: any;
      /** Repository type (monorepo, single-package) */
      'repository.type': string;
    };
  }

  /**
   * Event type for packages-discovered
   */
  export type Event = PackagesDiscovered;

  /**
   * Event name for packages-discovered
   */
  export type EventName = 'packages.discovered';
}

/**
 * Event type for node: canvases-discovered
 */
export namespace CanvasesDiscovered {
  /**
   * undefined
   */
  export interface CanvasesDiscovered {
    name: 'canvases.discovered';
    attributes: {
      /** Total canvas files found */
      'canvases.total': any;
      /** Regular .canvas files */
      'canvases.regular': any;
      /** OTEL .otel.canvas files */
      'canvases.otel': any;
      /** Canvas count per package */
      'canvases.byPackage'?: Record<string, any>;
    };
  }

  /**
   * Event type for canvases-discovered
   */
  export type Event = CanvasesDiscovered;

  /**
   * Event name for canvases-discovered
   */
  export type EventName = 'canvases.discovered';
}

/**
 * Event type for node: executions-discovered
 */
export namespace ExecutionsDiscovered {
  /**
   * undefined
   */
  export interface ExecutionsDiscovered {
    name: 'executions.discovered';
    attributes: {
      /** Total execution files found */
      'executions.total': any;
      /** Execution count per canvas */
      'executions.byCanvas'?: Record<string, any>;
    };
  }

  /**
   * Event type for executions-discovered
   */
  export type Event = ExecutionsDiscovered;

  /**
   * Event name for executions-discovered
   */
  export type EventName = 'executions.discovered';
}

/**
 * Event type for node: library-loaded
 */
export namespace LibraryLoaded {
  /**
   * undefined
   */
  export interface LibraryLoaded {
    name: 'library.loaded';
    attributes: {
      /** Whether library file exists */
      'library.found': boolean;
      /** Path to library file */
      'library.path'?: string;
      /** Number of node component types */
      'nodeComponents.count'?: any;
      /** Number of edge component types */
      'edgeComponents.count'?: any;
    };
  }

  /**
   * Event type for library-loaded
   */
  export type Event = LibraryLoaded;

  /**
   * Event name for library-loaded
   */
  export type EventName = 'library.loaded';
}

/**
 * Event type for node: discovery-complete
 */
export namespace DiscoveryComplete {
  /**
   * undefined
   */
  export interface DiscoveryComplete {
    name: 'discovery.complete';
    attributes: {
      /** Discovery duration in milliseconds */
      'discovery.duration'?: number;
      /** Total items discovered */
      'items.discovered': any;
    };
  }

  /**
   * Event type for discovery-complete
   */
  export type Event = DiscoveryComplete;

  /**
   * Event name for discovery-complete
   */
  export type EventName = 'discovery.complete';
}

/**
 * Event type for node: validation-started
 */
export namespace ValidationStarted {
  /**
   * undefined
   */
  export interface ValidationStarted {
    name: 'validation.started';
    attributes: {
      /** Type of validation (canvas, workflow, execution, library, config, rules, event) */
      'validation.type': string;
      /** Number of files to validate */
      'input.fileCount'?: any;
    };
  }

  /**
   * Event type for validation-started
   */
  export type Event = ValidationStarted;

  /**
   * Event name for validation-started
   */
  export type EventName = 'validation.started';
}

/**
 * Event type for node: file-parsed
 */
export namespace FileParsed {
  /**
   * undefined
   */
  export interface FileParsed {
    name: 'file.parsed';
    attributes: {
      /** Path to parsed file */
      'file.path': string;
      /** File format (json, yaml) */
      'file.format': string;
      /** File size in bytes */
      'file.size'?: any;
    };
  }

  /**
   * Event type for file-parsed
   */
  export type Event = FileParsed;

  /**
   * Event name for file-parsed
   */
  export type EventName = 'file.parsed';
}

/**
 * Event type for node: type-detected
 */
export namespace TypeDetected {
  /**
   * undefined
   */
  export interface TypeDetected {
    name: 'type.detected';
    attributes: {
      /** Detected validation type */
      'detected.type': string;
      /** How type was detected (file extension, content, explicit) */
      'detection.method'?: string;
    };
  }

  /**
   * Event type for type-detected
   */
  export type Event = TypeDetected;

  /**
   * Event name for type-detected
   */
  export type EventName = 'type.detected';
}

/**
 * Event type for node: canvas-validated
 */
export namespace CanvasValidated {
  /**
   * undefined
   */
  export interface CanvasValidated {
    name: 'canvas.validated';
    attributes: {
      /** Canvas type (standard, otel) */
      'canvas.type': string;
      /** Total validation checks performed */
      'checks.total': any;
      /** Checks that passed */
      'checks.passed': any;
      /** Checks that failed */
      'checks.failed': any;
      /** Number of nodes validated */
      'nodes.count'?: any;
      /** Number of edges validated */
      'edges.count'?: any;
    };
  }

  /**
   * Event type for canvas-validated
   */
  export type Event = CanvasValidated;

  /**
   * Event name for canvas-validated
   */
  export type EventName = 'canvas.validated';
}

/**
 * Event type for node: workflow-validated
 */
export namespace WorkflowValidated {
  /**
   * undefined
   */
  export interface WorkflowValidated {
    name: 'workflow.validated';
    attributes: {
      /** Number of scenarios validated */
      'scenarios.count': any;
      /** Total violations found */
      'violations.count': any;
      /** Error violations */
      'errors.count': any;
      /** Warning violations */
      'warnings.count': any;
    };
  }

  /**
   * Event type for workflow-validated
   */
  export type Event = WorkflowValidated;

  /**
   * Event name for workflow-validated
   */
  export type EventName = 'workflow.validated';
}

/**
 * Event type for node: execution-validated
 */
export namespace ExecutionValidated {
  /**
   * undefined
   */
  export interface ExecutionValidated {
    name: 'execution.validated';
    attributes: {
      /** Format detected (OTLP, ExecutionData) */
      'format': string;
      /** Number of spans validated */
      'spans.count': any;
      /** Total events across all spans */
      'events.count': any;
      /** Validation errors found */
      'errors.count': any;
    };
  }

  /**
   * Event type for execution-validated
   */
  export type Event = ExecutionValidated;

  /**
   * Event name for execution-validated
   */
  export type EventName = 'execution.validated';
}

/**
 * Event type for node: library-validated
 */
export namespace LibraryValidated {
  /**
   * undefined
   */
  export interface LibraryValidated {
    name: 'library.validated';
    attributes: {
      /** Number of node components */
      'nodeComponents.count': any;
      /** Number of edge components */
      'edgeComponents.count': any;
      /** Total issues found */
      'issues.count': any;
    };
  }

  /**
   * Event type for library-validated
   */
  export type Event = LibraryValidated;

  /**
   * Event name for library-validated
   */
  export type EventName = 'library.validated';
}

/**
 * Event type for node: rules-executed
 */
export namespace RulesExecuted {
  /**
   * undefined
   */
  export interface RulesExecuted {
    name: 'rules.executed';
    attributes: {
      /** Number of rules executed */
      'rules.count': any;
      /** Total violations found */
      'violations.total': any;
      /** Error-level violations */
      'violations.error': any;
      /** Warning-level violations */
      'violations.warning': any;
      /** Auto-fixable violations */
      'fixable.count'?: any;
    };
  }

  /**
   * Event type for rules-executed
   */
  export type Event = RulesExecuted;

  /**
   * Event name for rules-executed
   */
  export type EventName = 'rules.executed';
}

/**
 * Event type for node: results-aggregated
 */
export namespace ResultsAggregated {
  /**
   * undefined
   */
  export interface ResultsAggregated {
    name: 'results.aggregated';
    attributes: {
      /** Total files validated */
      'total.files': any;
      /** Total errors across all validations */
      'total.errors': any;
      /** Total warnings across all validations */
      'total.warnings': any;
      /** Types of validations performed */
      'validations.performed': any;
    };
  }

  /**
   * Event type for results-aggregated
   */
  export type Event = ResultsAggregated;

  /**
   * Event name for results-aggregated
   */
  export type EventName = 'results.aggregated';
}

/**
 * Event type for node: validation-complete
 */
export namespace ValidationComplete {
  /**
   * undefined
   */
  export interface ValidationComplete {
    name: 'validation.complete';
    attributes: {
      /** Overall validation result */
      'result.valid': boolean;
      /** Number of valid items */
      'result.validCount': any;
      /** Number of invalid items */
      'result.invalidCount': any;
      /** Total validation duration */
      'duration.ms'?: number;
    };
  }

  /**
   * Event type for validation-complete
   */
  export type Event = ValidationComplete;

  /**
   * Event name for validation-complete
   */
  export type EventName = 'validation.complete';
}

/**
 * Event type for node: validation-error
 */
export namespace ValidationError {
  /**
   * undefined
   */
  export interface ValidationError {
    name: 'validation.error';
    attributes: {
      /** Error type (parse, schema, reference, structure) */
      'error.type': string;
      /** Error message */
      'error.message': string;
      /** Stage where error occurred */
      'error.stage': string;
      /** File that caused the error */
      'error.file'?: string;
      /** Line number where error occurred */
      'error.line'?: any;
    };
  }

  /**
   * Event type for validation-error
   */
  export type Event = ValidationError;

  /**
   * Event name for validation-error
   */
  export type EventName = 'validation.error';
}

/**
 * Union of all event names in the canvas
 */
export type AllEventNames = 'analysis.started' | 'filetree.built' | 'packages.discovered' | 'canvases.discovered' | 'executions.discovered' | 'library.loaded' | 'discovery.complete' | 'validation.started' | 'file.parsed' | 'type.detected' | 'canvas.validated' | 'workflow.validated' | 'execution.validated' | 'library.validated' | 'rules.executed' | 'results.aggregated' | 'validation.complete' | 'validation.error';

/**
 * Type-safe event emitter for a specific node
 *
 * @example
 * ```typescript
 * const emit: NodeEmitter<GraphConverter.EventName, GraphConverter.Event> = ...
 * emit('conversion.started', {
 *   name: 'conversion.started',
 *   attributes: { ... }
 * });
 * ```
 */
export type NodeEmitter<
  TEventName extends string,
  TEvent extends { name: TEventName; attributes: Record<string, any> }
> = (event: TEvent) => void;

/**
 * Type-safe event emitter by event name
 *
 * @example
 * ```typescript
 * const emit: NodeEmitterByName<GraphConverter.Event> = ...
 * emit('conversion.started', {
 *   'config.nodeTypes': 2,
 *   'config.edgeTypes': 1
 * });
 * ```
 */
export type NodeEmitterByName<
  TEvent extends { name: string; attributes: Record<string, any> }
> = <TName extends TEvent['name']>(
  eventName: TName,
  attributes: Extract<TEvent, { name: TName }>['attributes']
) => void;